
development:
  adapter: postgresql
  encoding: unicode
  database: open-source-champion-api_development
  pool: 5
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: open-source-champion-api_test
  pool: 5
  password:
  timeout: 5000
